version: "3.9"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_produtos
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
    volumes:
      - sql_data:/var/opt/mssql

  produtos-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: produtos_api
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Server=${DB_HOST},1433;Database=${DB_NAME};User Id=${DB_USER};Password=${SA_PASSWORD};TrustServerCertificate=True;"
      MassTransit__Host: "rabbitmq"   # RabbitMQ externo
    depends_on:
      - sqlserver

volumes:
  sql_data:
