@ProdutosApi_HostAddress = https://localhost:7018

POST {{ProdutosApi_HostAddress}}/api/produtos
Accept: application/json
Content-Type: application/json

{
        "Nome":"Onion Rings",
        "Descricao":"350 gde aneis de cebola",
        "Preco":34.99,
        "CategoriaId":2
}
###
GET {{ProdutosApi_HostAddress}}/api/produtos
Accept: application/json

###

GET {{ProdutosApi_HostAddress}}/api/produtos/3
Accept: application/json

###
PUT {{ProdutosApi_HostAddress}}/api/produtos
Accept: application/json
Content-Type: application/json

{
        "Id":3,
        "Nome":"Porção de Batata",
        "Descricao":"Porção de batatas fritas tipo palito",
        "Preco":18.99,
        "CategoriaId":2
}

###
DELETE {{ProdutosApi_HostAddress}}/api/produtos/5
Accept: application/json